modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/qixils/minecraft-crowdcontrol/issues"
license = "MIT"
# TODO: more links

[[mods]]
modId = "crowdcontrol"
version = "${version}"
displayName = "Crowd Control"
authors = "qixils"
description = '''
The Ultimate Interactive Experience for Streamers
'''
logoFile = "assets/crowdcontrol/icon.png"

[[dependencies.crowdcontrol]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crowdcontrol]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crowdcontrol]]
modId = "luckperms"
type = "optional"
ordering = "AFTER"
side = "SERVER"
referralUrl = "https://luckperms.net/download"

[[dependencies.crowdcontrol]]
modId = "adventure_platform_neoforge"
type = "required"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "crowdcontrol.mixins.json"
